// Code generated by protoc-gen-go. DO NOT EDIT.
// source: learn/test_protobuf/proto_import/protocol/proto_main/student.proto

/*
Package student is a generated protocol buffer package.

It is generated from these files:
	learn/test_protobuf/proto_import/protocol/proto_main/student.proto

It has these top-level messages:
	Student
*/
package student

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import person "learn/test_protobuf/proto_import/protocol/proto_import"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Student struct {
	Person           *person.Person `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
	School           *string        `protobuf:"bytes,2,opt,name=school" json:"school,omitempty"`
	Grade            *string        `protobuf:"bytes,3,opt,name=grade" json:"grade,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Student) Reset()                    { *m = Student{} }
func (m *Student) String() string            { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()               {}
func (*Student) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Student) GetPerson() *person.Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Student) GetSchool() string {
	if m != nil && m.School != nil {
		return *m.School
	}
	return ""
}

func (m *Student) GetGrade() string {
	if m != nil && m.Grade != nil {
		return *m.Grade
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "student.Student")
}

func init() {
	proto.RegisterFile("learn/test_protobuf/proto_import/protocol/proto_main/student.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0xca, 0x49, 0x4d, 0x2c,
	0xca, 0xd3, 0x2f, 0x49, 0x2d, 0x2e, 0x89, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3,
	0x07, 0x33, 0xe2, 0x33, 0x73, 0x0b, 0xf2, 0x8b, 0x4a, 0x20, 0x9c, 0xe4, 0xfc, 0x1c, 0xa8, 0x68,
	0x6e, 0x62, 0x66, 0x9e, 0x7e, 0x71, 0x49, 0x69, 0x4a, 0x6a, 0x5e, 0x89, 0x1e, 0x58, 0x48, 0x88,
	0x1d, 0xca, 0x95, 0x72, 0x26, 0xd5, 0x30, 0x98, 0x68, 0x6a, 0x51, 0x71, 0x7e, 0x1e, 0xc4, 0x34,
	0xa5, 0x78, 0x2e, 0xf6, 0x60, 0x88, 0x79, 0x42, 0x6a, 0x5c, 0x6c, 0x10, 0x29, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0x6e, 0x23, 0x3e, 0x3d, 0xa8, 0xca, 0x00, 0x30, 0x15, 0x04, 0x95, 0x15, 0x12, 0xe3,
	0x62, 0x2b, 0x4e, 0xce, 0xc8, 0xcf, 0xcf, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2,
	0x84, 0x44, 0xb8, 0x58, 0xd3, 0x8b, 0x12, 0x53, 0x52, 0x25, 0x98, 0xc1, 0xc2, 0x10, 0x0e, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x21, 0xb9, 0x72, 0xdd, 0xf3, 0x00, 0x00, 0x00,
}
