# API version
apiVersion: apps/v1

# resource type
kind: Deployment

# metadata of the deployment
metadata:
  name: comments-v2
  labels:
    app: comments
    version: v2

# specification
spec:
  # need 1 replicas to run
  replicas: 1

  selector:
    matchLabels:
      app: comments
      version: v2

  # using this template to create pod
  template:
    metadata:
      labels:
        app: comments
        version: v2

    spec:
      # hostNetwork: true
      containers:
        - name: comments
          image: istio-test/comments:v1
          ports:
            - containerPort: 9998
          resources:
            requests:
              cpu: 0.2
              memory: "56Mi"
            limits:
              cpu: 1
              memory: "128Mi"
      restartPolicy: Always
