#API version
apiVersion: v1

#Resource type
kind: Service

#Metadata of the service
metadata:
  name: comments

#Specification
spec:
  type: ClusterIP

  ports:
    - name: http
      port: 9998
      protocol: TCP
      targetPort: 9998

  selector:
    app: comments
