// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package person2 is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	PhoneNumber
	Address
	Person
*/
package person2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) Enum() *PhoneType {
	p := new(PhoneType)
	*p = x
	return p
}
func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}
func (x *PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PhoneType_value, data, "PhoneType")
	if err != nil {
		return err
	}
	*x = PhoneType(value)
	return nil
}
func (PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PhoneNumber struct {
	StrNumber        *string    `protobuf:"bytes,1,req,name=str_number,json=strNumber" json:"str_number,omitempty"`
	EnumType         *PhoneType `protobuf:"varint,2,opt,name=enum_type,json=enumType,enum=person2.PhoneType,def=1" json:"enum_type,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_PhoneNumber_EnumType PhoneType = PhoneType_HOME

func (m *PhoneNumber) GetStrNumber() string {
	if m != nil && m.StrNumber != nil {
		return *m.StrNumber
	}
	return ""
}

func (m *PhoneNumber) GetEnumType() PhoneType {
	if m != nil && m.EnumType != nil {
		return *m.EnumType
	}
	return Default_PhoneNumber_EnumType
}

type Address struct {
	StrBlock         *string `protobuf:"bytes,1,req,name=str_block,json=strBlock" json:"str_block,omitempty"`
	ZipCode          *string `protobuf:"bytes,2,req,name=zip_code,json=zipCode" json:"zip_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetStrBlock() string {
	if m != nil && m.StrBlock != nil {
		return *m.StrBlock
	}
	return ""
}

func (m *Address) GetZipCode() string {
	if m != nil && m.ZipCode != nil {
		return *m.ZipCode
	}
	return ""
}

type Person struct {
	StrName          *string        `protobuf:"bytes,1,req,name=str_name,json=strName" json:"str_name,omitempty"`
	Int32Id          *int32         `protobuf:"varint,2,req,name=int32_id,json=int32Id" json:"int32_id,omitempty"`
	StrEmail         *string        `protobuf:"bytes,3,opt,name=str_email,json=strEmail" json:"str_email,omitempty"`
	RptPhone         []*PhoneNumber `protobuf:"bytes,4,rep,name=rpt_phone,json=rptPhone" json:"rpt_phone,omitempty"`
	Address          *Address       `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Person) GetStrName() string {
	if m != nil && m.StrName != nil {
		return *m.StrName
	}
	return ""
}

func (m *Person) GetInt32Id() int32 {
	if m != nil && m.Int32Id != nil {
		return *m.Int32Id
	}
	return 0
}

func (m *Person) GetStrEmail() string {
	if m != nil && m.StrEmail != nil {
		return *m.StrEmail
	}
	return ""
}

func (m *Person) GetRptPhone() []*PhoneNumber {
	if m != nil {
		return m.RptPhone
	}
	return nil
}

func (m *Person) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*PhoneNumber)(nil), "person2.PhoneNumber")
	proto.RegisterType((*Address)(nil), "person2.Address")
	proto.RegisterType((*Person)(nil), "person2.Person")
	proto.RegisterEnum("person2.PhoneType", PhoneType_name, PhoneType_value)
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0x7e, 0xb5, 0x7d, 0x13, 0x29, 0xc1, 0x43, 0x45, 0x84, 0xb2, 0x53, 0x99, 0x30,
	0xb0, 0xe2, 0xc5, 0xdb, 0x26, 0x03, 0x87, 0xce, 0x8d, 0x20, 0x78, 0x0c, 0xdd, 0x12, 0xb0, 0xb8,
	0x36, 0x21, 0xc9, 0x0e, 0xdb, 0x9f, 0xe6, 0x5f, 0x27, 0x2f, 0xcd, 0x06, 0xde, 0xf2, 0xe1, 0xbd,
	0x7c, 0xde, 0xfb, 0x3e, 0xb8, 0x54, 0x42, 0x1b, 0xd9, 0x4c, 0x94, 0x96, 0x56, 0x92, 0xb0, 0xa5,
	0x62, 0xb4, 0x85, 0xe1, 0xfa, 0x5b, 0x36, 0xe2, 0x63, 0x5f, 0x6f, 0x84, 0x26, 0x77, 0x00, 0xc6,
	0x6a, 0xd6, 0x38, 0x4a, 0x83, 0xac, 0x93, 0xc7, 0x34, 0x36, 0x56, 0xfb, 0xf2, 0x13, 0xc4, 0xa2,
	0xd9, 0xd7, 0xcc, 0x1e, 0x94, 0x48, 0x3b, 0x59, 0x90, 0x5f, 0x15, 0x64, 0xe2, 0x55, 0x13, 0xe7,
	0xf9, 0x3c, 0x28, 0xf1, 0xdc, 0x7b, 0x5d, 0x2d, 0xe7, 0x34, 0xc2, 0x56, 0xe4, 0xd1, 0x14, 0xc2,
	0x29, 0xe7, 0x5a, 0x18, 0x43, 0x6e, 0x01, 0x75, 0x6c, 0xb3, 0x93, 0xdb, 0x1f, 0xef, 0x8f, 0x8c,
	0xd5, 0x33, 0x64, 0x72, 0x03, 0xd1, 0xb1, 0x52, 0x6c, 0x2b, 0x39, 0xda, 0xb1, 0x16, 0x1e, 0x2b,
	0xf5, 0x22, 0xb9, 0x18, 0xfd, 0x06, 0x30, 0x58, 0xbb, 0x41, 0xd8, 0xe5, 0x76, 0x2c, 0x6b, 0xe1,
	0x0d, 0x21, 0x6e, 0x58, 0xd6, 0x02, 0x4b, 0x55, 0x63, 0x1f, 0x0b, 0x56, 0x71, 0x27, 0xe8, 0xd3,
	0xd0, 0xf1, 0x82, 0x9f, 0x06, 0x8b, 0xba, 0xac, 0x76, 0x69, 0x37, 0x0b, 0xfc, 0xe0, 0x39, 0x32,
	0x79, 0x80, 0x58, 0x2b, 0xcb, 0x14, 0x26, 0x48, 0x7b, 0x59, 0x37, 0x1f, 0x16, 0xd7, 0xff, 0x73,
	0xb5, 0x07, 0xa0, 0x91, 0x56, 0xd6, 0x31, 0x19, 0x43, 0x58, 0xb6, 0x99, 0xd2, 0x7e, 0x16, 0xe4,
	0xc3, 0x22, 0x39, 0x7f, 0xf0, 0x59, 0xe9, 0xa9, 0x61, 0x7c, 0x0f, 0xf1, 0xf9, 0x38, 0x04, 0x60,
	0xb0, 0x5c, 0xcd, 0x16, 0xef, 0xf3, 0xe4, 0x82, 0x44, 0xe0, 0x4e, 0x95, 0x04, 0xf8, 0xfa, 0x5a,
	0xd1, 0xb7, 0xa4, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x97, 0xdb, 0x09, 0x7d, 0xa9, 0x01, 0x00,
	0x00,
}
