
# API version
apiVersion: apps/v1

# resource type
kind: Deployment

# metadata of the deployment
metadata:
  name: user
  labels:
    app: user
    version: v1

# specification
spec:
  # replica number to run
  replicas: 1

  selector:
    matchLabels:
      app: user
      version: v1

  # using this template to create pod
  template:
    metadata:
      labels:
        app: user
        version: v1

    spec:
      containers:
        - name: user
          image: istio-test/user:v1
          ports:
            - containerPort: 9999
      restartPolicy: Always

  ##########################################
  # More features and details, please visit 
  #     'https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/'
  # to get more information, this URL is for kubernetes v1.17 only
  ##########################################
