// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package person3 is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	PersonInfo
*/
package person3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonInfo_PhoneType int32

const (
	PersonInfo_MOBILE PersonInfo_PhoneType = 0
	PersonInfo_HOME   PersonInfo_PhoneType = 1
	PersonInfo_WORK   PersonInfo_PhoneType = 2
)

var PersonInfo_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PersonInfo_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PersonInfo_PhoneType) String() string {
	return proto.EnumName(PersonInfo_PhoneType_name, int32(x))
}
func (PersonInfo_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PersonInfo struct {
	Name  string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    int32                     `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email string                    `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone []*PersonInfo_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
}

func (m *PersonInfo) Reset()                    { *m = PersonInfo{} }
func (m *PersonInfo) String() string            { return proto.CompactTextString(m) }
func (*PersonInfo) ProtoMessage()               {}
func (*PersonInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PersonInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PersonInfo) GetPhone() []*PersonInfo_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type PersonInfo_PhoneNumber struct {
	Number string               `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   PersonInfo_PhoneType `protobuf:"varint,2,opt,name=type,enum=person3.PersonInfo_PhoneType" json:"type,omitempty"`
}

func (m *PersonInfo_PhoneNumber) Reset()                    { *m = PersonInfo_PhoneNumber{} }
func (m *PersonInfo_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PersonInfo_PhoneNumber) ProtoMessage()               {}
func (*PersonInfo_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PersonInfo_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PersonInfo_PhoneNumber) GetType() PersonInfo_PhoneType {
	if m != nil {
		return m.Type
	}
	return PersonInfo_MOBILE
}

func init() {
	proto.RegisterType((*PersonInfo)(nil), "person3.PersonInfo")
	proto.RegisterType((*PersonInfo_PhoneNumber)(nil), "person3.PersonInfo.PhoneNumber")
	proto.RegisterEnum("person3.PersonInfo_PhoneType", PersonInfo_PhoneType_name, PersonInfo_PhoneType_value)
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xf0, 0x8c, 0x95, 0x5a, 0x98,
	0xb8, 0xb8, 0x02, 0xc0, 0x6c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x88, 0x29, 0x33, 0x45, 0x48, 0x84, 0x8b, 0x35, 0x35, 0x37,
	0x31, 0x33, 0x47, 0x82, 0x19, 0xac, 0x08, 0xc2, 0x11, 0x32, 0xe5, 0x62, 0x2d, 0xc8, 0xc8, 0xcf,
	0x4b, 0x95, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd7, 0x83, 0xda, 0xa0, 0x87, 0x30, 0x5d,
	0x2f, 0x00, 0xa4, 0xc0, 0xaf, 0x34, 0x37, 0x29, 0xb5, 0x28, 0x08, 0xa2, 0x5a, 0x2a, 0x82, 0x8b,
	0x1b, 0x49, 0x54, 0x48, 0x8c, 0x8b, 0x2d, 0x0f, 0xcc, 0x82, 0xba, 0x00, 0xca, 0x13, 0x32, 0xe4,
	0x62, 0x29, 0xa9, 0x2c, 0x48, 0x05, 0xbb, 0x82, 0xcf, 0x48, 0x16, 0xa7, 0xe1, 0x21, 0x95, 0x05,
	0xa9, 0x41, 0x60, 0xa5, 0x4a, 0xda, 0x5c, 0x9c, 0x70, 0x21, 0x21, 0x2e, 0x2e, 0x36, 0x5f, 0x7f,
	0x27, 0x4f, 0x1f, 0x57, 0x01, 0x06, 0x21, 0x0e, 0x2e, 0x16, 0x0f, 0x7f, 0x5f, 0x57, 0x01, 0x46,
	0x10, 0x2b, 0xdc, 0x3f, 0xc8, 0x5b, 0x80, 0x29, 0x89, 0x0d, 0x1c, 0x2c, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x30, 0xf4, 0xcc, 0x26, 0x01, 0x00, 0x00,
}
