# API version
apiVersion: v1

# resource type
kind: Service

# metadata of the service
metadata:
  name: goods

# specification
spec:
  type: NodePort    # since istio's gateway failed to work, so expose NodePort to let traffic in

  ports:
    - name: http
      port: 9996
      protocol: TCP
      targetPort: 9996

  selector:
    app: goods
