#API version
apiVersion: extensions/v1beta1

#Resource type
kind: Ingress

#Metadata of the service
metadata:
  name: my-nginx-ingress

#Specification
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx-service
          servicePort: 80
