apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: goods-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-goods
        protocol: HTTP
      hosts:
      - "*"

