// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf_spec/user/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	api/protobuf_spec/user/user.proto

It has these top-level messages:
	UserInfo
	GetUserRequest
	GetUserResponse
	GetUserBatchRequest
	GetUserBatchResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Pic  string `protobuf:"bytes,3,opt,name=pic" json:"pic,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	UserInfo *UserInfo `protobuf:"bytes,1,opt,name=userInfo" json:"userInfo,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserResponse) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type GetUserBatchRequest struct {
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *GetUserBatchRequest) Reset()                    { *m = GetUserBatchRequest{} }
func (m *GetUserBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserBatchRequest) ProtoMessage()               {}
func (*GetUserBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserBatchRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUserBatchResponse struct {
	UserInfos []*UserInfo `protobuf:"bytes,1,rep,name=userInfos" json:"userInfos,omitempty"`
}

func (m *GetUserBatchResponse) Reset()                    { *m = GetUserBatchResponse{} }
func (m *GetUserBatchResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserBatchResponse) ProtoMessage()               {}
func (*GetUserBatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserBatchResponse) GetUserInfos() []*UserInfo {
	if m != nil {
		return m.UserInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*GetUserBatchRequest)(nil), "user.GetUserBatchRequest")
	proto.RegisterType((*GetUserBatchResponse)(nil), "user.GetUserBatchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error) {
	out := new(GetUserBatchResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUserBatch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserBatch(context.Context, *GetUserBatchRequest) (*GetUserBatchResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserBatch(ctx, req.(*GetUserBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserBatch",
			Handler:    _UserService_GetUserBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf_spec/user/user.proto",
}

func init() { proto.RegisterFile("api/protobuf_spec/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x75, 0xb3, 0x45, 0xdb, 0xa9, 0xc4, 0x32, 0x56, 0x88, 0x39, 0xc5, 0xbd, 0x18, 0x44, 0x5a,
	0xa8, 0x17, 0x2f, 0x82, 0x88, 0x50, 0xbc, 0xae, 0x78, 0x96, 0x34, 0x99, 0xe2, 0x1e, 0x4c, 0xd6,
	0x6c, 0xe2, 0x77, 0xf8, 0xc9, 0xb2, 0x9b, 0xa4, 0x36, 0xb1, 0x97, 0xe5, 0xf1, 0xe6, 0xcd, 0x7b,
	0x6f, 0x58, 0xb8, 0x4a, 0xb4, 0x5a, 0xea, 0xb2, 0xa8, 0x8a, 0x4d, 0xbd, 0x7d, 0x37, 0x9a, 0xd2,
	0x65, 0x6d, 0xa8, 0x74, 0xcf, 0xc2, 0xf1, 0x38, 0xb2, 0x58, 0x3c, 0xc2, 0xf8, 0xcd, 0x50, 0xf9,
	0x92, 0x6f, 0x0b, 0xf4, 0xc1, 0x53, 0x59, 0xc0, 0x22, 0x16, 0x73, 0xe9, 0xa9, 0x0c, 0x11, 0x46,
	0x79, 0xf2, 0x49, 0x81, 0x17, 0xb1, 0x78, 0x22, 0x1d, 0xc6, 0x19, 0x70, 0xad, 0xd2, 0x80, 0x3b,
	0xca, 0x42, 0x11, 0x81, 0xbf, 0xa6, 0xca, 0x9a, 0x48, 0xfa, 0xaa, 0xc9, 0x54, 0x43, 0x1f, 0xf1,
	0x00, 0x67, 0x3b, 0x85, 0xd1, 0x45, 0x6e, 0x08, 0x6f, 0x60, 0x5c, 0xb7, 0xb1, 0x4e, 0x38, 0x5d,
	0xf9, 0x0b, 0xd7, 0xad, 0x2b, 0x23, 0x77, 0x73, 0x71, 0x0d, 0xe7, 0xed, 0xfa, 0x53, 0x52, 0xa5,
	0x1f, 0x5d, 0xca, 0x0c, 0xb8, 0xca, 0x4c, 0xc0, 0x22, 0x1e, 0x73, 0x69, 0xa1, 0x78, 0x86, 0x79,
	0x5f, 0xd8, 0x86, 0xdd, 0xc2, 0xa4, 0x33, 0x6b, 0xf4, 0xff, 0xd3, 0xfe, 0x04, 0xab, 0x1f, 0x06,
	0x53, 0xcb, 0xbf, 0x52, 0xf9, 0xad, 0x52, 0xc2, 0x7b, 0x38, 0x69, 0x5d, 0x71, 0xde, 0x6c, 0xf5,
	0xcf, 0x0d, 0x2f, 0x06, 0x6c, 0x93, 0x2a, 0x8e, 0x70, 0x0d, 0xa7, 0xfb, 0x7d, 0xf0, 0xb2, 0x27,
	0xdc, 0x3f, 0x26, 0x0c, 0x0f, 0x8d, 0x3a, 0xa3, 0xcd, 0xb1, 0xfb, 0xb1, 0xbb, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0xd5, 0x3d, 0x05, 0xd6, 0x01, 0x00, 0x00,
}
