# API version
apiVersion: v1

# resource type
kind: Service

# metadata of the service
metadata:
  name: stock

# specification
spec:
  type: ClusterIP

  ports:
    - name: http
      port: 9997
      protocol: TCP
      targetPort: 9997

  selector:
    app: stock
