#API version
apiVersion: extensions/v1beta1

#Resource type
kind: DaemonSet

#Metadata of this daemon set
metadata:
  name: my-nginx-daemon
  namespace: default
  labels:
    app: nginx-daemon

#Specification
spec:
  #Using this template to create pod
  template:
    metadata:
      labels:
        name: my-nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
