apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: my-nginx-daemon
  namespace: default
  labels:
    app: nginx-daemon
spec:
  template:
    metadata:
      labels:
        name: my-nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
