// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package person is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	Person
*/
package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string               `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone            []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*Person_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=person.Person_PhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

const Default_Person_PhoneNumber_Type Person_PhoneType = Person_HOME

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Person_PhoneNumber_Type
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "person.Person.PhoneNumber")
	proto.RegisterEnum("person.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xae, 0x31, 0x72,
	0xb1, 0x05, 0x80, 0x99, 0x42, 0x3c, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x4c,
	0x1a, 0x9c, 0x42, 0x5c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0xac, 0x42, 0xbc,
	0x5c, 0xac, 0xa9, 0xb9, 0x89, 0x99, 0x39, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x42, 0x9a, 0x5c,
	0xac, 0x05, 0x19, 0xf9, 0x79, 0xa9, 0x12, 0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x50,
	0x93, 0x03, 0xa0, 0x14, 0x48, 0xce, 0xaf, 0x34, 0x37, 0x29, 0xb5, 0x48, 0xca, 0x9b, 0x8b, 0x1b,
	0x89, 0x2b, 0xc4, 0xc7, 0xc5, 0x96, 0x07, 0x66, 0x41, 0x2d, 0xd1, 0xe1, 0x62, 0x29, 0xa9, 0x2c,
	0x48, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x33, 0x92, 0xc0, 0x66, 0x50, 0x48, 0x65, 0x41, 0xaa,
	0x15, 0x8b, 0x87, 0xbf, 0xaf, 0xab, 0x92, 0x36, 0x17, 0x27, 0x5c, 0x48, 0x88, 0x8b, 0x8b, 0xcd,
	0xd7, 0xdf, 0xc9, 0xd3, 0xc7, 0x55, 0x80, 0x41, 0x88, 0x83, 0x0b, 0xac, 0x40, 0x80, 0x11, 0xc4,
	0x0a, 0xf7, 0x0f, 0xf2, 0x16, 0x60, 0x02, 0x04, 0x00, 0x00, 0xff, 0xff, 0xda, 0x52, 0xc1, 0xea,
	0xef, 0x00, 0x00, 0x00,
}
