// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package person is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	Person
*/
package person

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name  string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    int32                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*Person_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=person.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "person.Person.PhoneNumber")
	proto.RegisterEnum("person.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xbe, 0x31, 0x72,
	0xb1, 0x05, 0x80, 0x99, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x6b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x08, 0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x33,
	0x58, 0x11, 0x84, 0x23, 0x64, 0xc0, 0xc5, 0x5a, 0x90, 0x91, 0x9f, 0x97, 0x2a, 0xc1, 0xa2, 0xc0,
	0xac, 0xc1, 0x6d, 0x24, 0xa5, 0x07, 0xb5, 0x2a, 0x00, 0x4a, 0x81, 0xe4, 0xfc, 0x4a, 0x73, 0x93,
	0x52, 0x8b, 0x82, 0x20, 0x0a, 0xa5, 0x82, 0xb9, 0xb8, 0x91, 0x44, 0x85, 0xc4, 0xb8, 0xd8, 0xf2,
	0xc0, 0x2c, 0xa8, 0xe5, 0x50, 0x9e, 0x90, 0x0e, 0x17, 0x4b, 0x49, 0x65, 0x41, 0x2a, 0xd8, 0x01,
	0x7c, 0x46, 0x12, 0xd8, 0xcc, 0x0d, 0xa9, 0x2c, 0x48, 0x0d, 0x02, 0xab, 0x52, 0xd2, 0xe6, 0xe2,
	0x84, 0x0b, 0x09, 0x71, 0x71, 0xb1, 0xf9, 0xfa, 0x3b, 0x79, 0xfa, 0xb8, 0x0a, 0x30, 0x08, 0x71,
	0x70, 0xb1, 0x78, 0xf8, 0xfb, 0xba, 0x0a, 0x30, 0x82, 0x58, 0xe1, 0xfe, 0x41, 0xde, 0x02, 0x4c,
	0x49, 0x6c, 0xe0, 0x70, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x02, 0x53, 0xe0, 0x76, 0x17,
	0x01, 0x00, 0x00,
}
